name: at_crdt_demo
description: A sample command-line application.
version: 1.0.0
publish: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

dependencies:
  at_cli_commons: ^1.0.4
  at_client: ^3.0.75
  chalkdart: ^2.2.1
  crdt: ^5.1.2
  uuid: ^4.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  mocktail: ^1.0.3

dependency_overrides:
  uuid: ^4.0.3 # at_client vs crdt
